ci: fixed pull_request

diff --git a/.github/workflows/pull_request.yaml b/.github/workflows/pull_request.yaml
--- a/.github/workflows/pull_request.yaml
+++ b/.github/workflows/pull_request.yaml
@@ -43,46 +43,46 @@ jobs:
       services:
 
       # Label used to access the service container
-        # redis:
-        #   # Docker Hub image
-        #   image: bitnami/redis:6.2.7
-        #   # Provide the password for postgres
-        #   env:
-        #     REDIS_ENABLE_SSL_AUTH: false
-        #     REDIS_GEOCODING_INDEX: 0
-        #     REDIS_TTL_INDEX: 1
-        #     REDIS_TTL: 2
-        #     ALLOW_EMPTY_PASSWORD: yes
-        #   ports: 
-        #     - 6379:6379
-
-        #   # Set health checks to wait until postgres has started
-        #   options: >-
-        #     --health-cmd "redis-cli -h redis ping"
-        #     --health-interval 10s
-        #     --health-timeout 5s
-        #     --health-retries 5
-            
-        # Label used to access the service container
         redis:
           # Docker Hub image
-          image: redis
+          image: bitnami/redis:6.2.7
           # Provide the password for postgres
           env:
-            # REDIS_HOST: redis
-            # REDIS_ENABLE_SSL_AUTH: false
+            REDIS_ENABLE_SSL_AUTH: false
             # REDIS_GEOCODING_INDEX: 0
             # REDIS_TTL_INDEX: 1
             # REDIS_TTL: 2
             ALLOW_EMPTY_PASSWORD: yes
           ports: 
             - 6379:6379
+
           # Set health checks to wait until postgres has started
           options: >-
-            --health-cmd "redis-cli ping"
+            --health-cmd "redis-cli -h redis ping || exit 1"
             --health-interval 10s
             --health-timeout 5s
             --health-retries 5
+            
+        # Label used to access the service container
+        # redis:
+        #   # Docker Hub image
+        #   image: redis
+        #   # Provide the password for postgres
+        #   env:
+        #     # REDIS_HOST: redis
+        #     REDIS_ENABLE_SSL_AUTH: false
+        #     # REDIS_GEOCODING_INDEX: 0
+        #     # REDIS_TTL_INDEX: 1
+        #     # REDIS_TTL: 2
+        #     ALLOW_EMPTY_PASSWORD: yes
+        #   ports: 
+        #     - 6379:6379
+        #   # Set health checks to wait until postgres has started
+        #   options: >-
+        #     --health-cmd "redis-cli ping"
+        #     --health-interval 10s
+        #     --health-timeout 5s
+        #     --health-retries 5
         
         zookeeper:
             image: bitnami/zookeeper:3.8.0
@@ -108,7 +108,7 @@ jobs:
 
       strategy:
         matrix:
-          node: [14.x, 16.x]
+          node: [18.x, 20.x]
 
       steps:
         - name: Check out Git repository
@@ -154,12 +154,23 @@ jobs:
         #       sleep 5;
         #     done
 
+        # - name: Wait for Redis
+        #   run: |
+        #     until docker exec $(docker ps -qf "name=redis") redis-cli ping; do
+        #       echo "Waiting for Redis to be ready...";
+        #       sleep 5;
+        #     done
+
         - name: Wait for Redis
           run: |
             until docker exec $(docker ps -qf "name=redis") redis-cli ping; do
               echo "Waiting for Redis to be ready...";
               sleep 5;
             done
+
+        - name: Configure Redis Keyspace Notifications
+          run: |
+            docker exec $(docker ps -qf "name=redis") redis-cli config set notify-keyspace-events KEA
 
 
         # - name: Redis set Pub-Sub config
@@ -170,9 +181,9 @@ jobs:
         #     docker exec $(docker ps -qf "name=redis") redis-cli select 1
         #     docker exec $(docker ps -qf "name=redis") redis-cli config set notify-keyspace-events KEA
 
-        - name: Redis set Pub-Sub config
-          run: |
-            docker exec $(docker ps -qf "name=redis") redis-cli config set notify-keyspace-events KEA       
+        # - name: Redis set Pub-Sub config
+        #   run: |
+        #     docker exec $(docker ps -qf "name=redis") redis-cli config set notify-keyspace-events KEA       
 
         # - name: Redis set Pub-Sub config
         #   run: |
